#include "../lib/_all.inc"
#include "_all.qh"

#include "../common/effects/qc/all.qc"

#include "anticheat.qc"
#include "antilag.qc"
#include "campaign.qc"
#include "cheats.qc"
#include "cl_client.qc"
#include "cl_impulse.qc"
#include "cl_player.qc"
#include "g_damage.qc"
#include "g_hook.qc"
// #include "g_lights.qc" // TODO: was never used
#include "g_models.qc"
#include "g_subs.qc"
#include "g_world.qc"
#include "ipban.qc"
#include "item_key.qc"
#include "mapvoting.qc"
#include "miscfunctions.qc"
#include "movelib.qc"
#include "playerdemo.qc"
#include "portals.qc"
#include "race.qc"
#include "round_handler.qc"
#include "scores.qc"
#include "scores_rules.qc"
#include "spawnpoints.qc"
#include "steerlib.qc"
#include "sv_main.qc"
#include "teamplay.qc"
#include "t_halflife.qc"
#include "t_items.qc"
#include "t_quake3.qc"
#include "t_quake.qc"

#include "bot/_all.inc"

#include "command/all.qc"

#include "pathlib/_all.inc"

#include "weapons/accuracy.qc"
#include "weapons/common.qc"
#include "weapons/csqcprojectile.qc" // TODO
#include "weapons/hitplot.qc"
#include "weapons/selection.qc"
#include "weapons/spawning.qc"
#include "weapons/throwing.qc"
#include "weapons/tracing.qc"
#include "weapons/weaponstats.qc"
#include "weapons/weaponsystem.qc"

#include "../common/anim.qc"
#include "../common/animdecide.qc"
#include "../common/campaign_file.qc"
#include "../common/campaign_setup.qc"
#include "../common/effects/effectinfo.qc"
#include "../common/ent_cs.qc"
#include "../common/mapinfo.qc"
#include "../common/minigames/minigames.qc"
#include "../common/minigames/sv_minigames.qc"
#include "../common/monsters/spawn.qc"
#include "../common/monsters/sv_monsters.qc"
#include "../common/movetypes/include.qc"
#include "../common/net_notice.qc"
#include "../common/notifications.qc"
#include "../common/physics.qc"
#include "../common/playerstats.qc"
#include "../common/triggers/include.qc"
#include "../common/util.qc"
#include "../common/viewloc.qc"

#include "../common/deathtypes/all.qc"
#include "../common/effects/all.qc"
#include "../common/gamemodes/all.qc"
#include "../common/impulses/all.qc"
#include "../common/items/all.qc"
#include "../common/monsters/all.qc"
#include "../common/turrets/all.qc"
#include "../common/vehicles/all.qc"
#include "../common/weapons/all.qc"
#include "../common/mutators/all.qc"
#include "mutators/all.qc"

#include "../common/turrets/sv_turrets.qc"
#include "../common/turrets/config.qc"
#include "../common/turrets/util.qc"
#include "../common/turrets/checkpoint.qc"
#include "../common/turrets/targettrigger.qc"
#include "../common/weapons/config.qc"

#include "../lib/csqcmodel/sv_model.qc"

#include "../lib/warpzone/anglestransform.qc"
#include "../lib/warpzone/common.qc"
#include "../lib/warpzone/server.qc"
#include "../lib/warpzone/util_server.qc"

#if BUILD_MOD
#include "../../mod/server/progs.inc"
#endif
