if (${CMAKE_VERSION} VERSION_LESS "3.4")
    set(_CMAKE_ASM_INCLUDES "")
else()
    set(_CMAKE_ASM_INCLUDES "<INCLUDES>")
endif()
mark_as_advanced(_CMAKE_ASM_INCLUDES)

set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> compile <OBJECT> <DEFINES> -DGMQCC ${_CMAKE_ASM_INCLUDES} <FLAGS> <SOURCE>")
set(CMAKE_ASM_LINK_EXECUTABLE "env CMAKE_EXECUTABLE_SUFFIX=${CMAKE_EXECUTABLE_SUFFIX} <CMAKE_ASM_COMPILER> link <OBJECTS> -o <TARGET>")

set(CMAKE_INCLUDE_FLAG_ASM "-I")
set(CMAKE_INCLUDE_FLAG_ASM_SEP "")
set(CMAKE_EXECUTABLE_PREFIX_ASM "")
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".dat")
