# TODO: <DEFINES> <INCLUDES> <FLAGS>
set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> compile <OBJECT> <DEFINES> -DGMQCC <FLAGS> <SOURCE>")
set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_ASM_COMPILER> link <OBJECTS> -o <TARGET>")

set(CMAKE_INCLUDE_FLAG_ASM "-I")
set(CMAKE_INCLUDE_FLAG_ASM_SEP "")
set(CMAKE_EXECUTABLE_PREFIX_ASM "")
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".dat")
